title: "Sesgos generales en elecciones federales"
author: "Alejandro Reyes"
output:
  html_document:

Having standarized the results, we can start exploring these data:

```{r, fig.height=2.5}

load("../data/standarizedData.rda")

plotPollsRes <- function( encuesta, resultados=NULL, fechaLim ){
  pl <- encuesta %>% 
    filter( Date >= fechaLim ) %>%
    melt( value.name="percent", id.vars=c("pollster", "Date")) %>% 
    group_by( variable ) %>%
    summarize( mean=mean(percent), se=sd(percent)/sqrt(n()) ) %>%
    rename(`Candidate`=variable) %>% 
    mutate( type="encuestas" )
  if( !is.null( resultados ) ){
    resultados <- cbind( rename( resultados, mean=Result), se=NA, type="resultado")
    pl <- rbind( pl, resultados )
  }
    mutate( pl, Candidate=fct_reorder(Candidate, mean, .desc = FALSE), 
            start=mean-1.96*se, end=mean+1.96*se ) %>%
    ggplot( aes( Candidate, mean, col=type ) ) +
      geom_point(show.legend=TRUE) +
      geom_errorbar( aes(ymin=start, ymax=end), width=.15) + coord_flip() +
      labs( y="Porcentaje de votos", x="Candidato" )
}

encuesta <- encuestas2006
fechaLim = "2006-06-01"
resultados <- resultados2006


pl <- plotPollsRes( encuestas2006, resultados2006, fechaLim="2006-06-01" ) +
  ylim(22, 38) + ggtitle( "Elecciones MX 2006" ) + 
  labs(x="", col="") + 
  scale_x_discrete( labels = c("Madrazo", "Calderón", "AMLO") ) +
  theme(legend.pos="top") + scale_colour_manual(values=c("#4d4d4d","red"))

save_plot(pl, file="elecciones2006_bias.png", base_aspect_ratio = 1.4, base_height=2.8)

plotPollsRes( encuestas2012, resultados2012, fechaLim="2012-06-01" ) +
  ggtitle( "2012")

plotPollsRes( encuestas2018, fechaLim="2018-01-01") + 
  ggtitle("2018") + ylim(10, 45)

```


```{r trendsOvertime}

encuesta <- encuestas2006

plotTrends <- function( encuesta, fechaLim=NULL ){
  melt( encuesta, id.vars=c("Date", "pollster") ) %>%
    rename( Candidato=variable ) %>%
    filter( Date >= fechaLim ) %>%
    ggplot( aes( Date, value, col=Candidato ) ) +
    geom_point() + geom_smooth() + ylab("Porcentage de votos")
}

plotTrends( encuestas2006, fechaLim="2006-01-01" )

plotTrends( encuestas2012, fechaLim="2012-01-01" )

plotTrends( encuestas2018, fechaLim="2017-11-01" ) 

```